# Week 11 Homework

Write a class that generates fake data.

* Write the code under the py docs ( do NOT remove docs strings)
* Before comitting do a Restart & Run All

Make sure that if a dataframe is passed in, it should not remove any value from it.

In [13]:
import pandas as pd
import random
from faker import Faker

In [14]:
class FakeDataGenerator:
    
    def __init__(self, df = None, rows=5):
        """
        This class generates fake data
        
        If data frame is passed in it will add the fake data to it. 
        Otherwise, it will create a new data frame
        
        Parameters:
        -----------
        df: 
          DataFrame default is None
          
        rows:
          If df None, this parameter will be used to create a data frame with `row` length
        """
        # code goes under this line. 
        # I will deduct points if any code is written above the comments!
          
        self.data = Faker()
        
        if df is not None:
            self.df = df
            self.rows = len(df)
        else:
            self.df = pd.DataFrame()
            self.rows = rows
        
        
    def add_random_number(self, column_name, small_value, high_value): # optional: add probabilities 
        """
        adds fake numbers to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [random.randint(small_value,high_value) for i in range(self.rows)]
        
        return self.df       
    
        
    def add_name(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """

        self.df[column_name] = [self.data.first_name() for i in range(self.rows)]
        
        return self.df
    
    
    def add_last_name(self, column_name):
        """
        adds fake last name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.data.last_name() for i in range(self.rows)]
        
        return self.df
    
    
    def add_email(self, column_name):
        """
        adds fake email to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """

        self.df[column_name] = [self.data.email() for i in range(self.rows)]
        
        return self.df
    
    
    def add_phone_number(self, column_name):
        """
        adds fake phone number to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.data.phone_number() for i in range(self.rows)]
        
        return self.df
    
    
    def add_address(self, column_name):
        """
        adds fake address to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.data.address() for i in range(self.rows)]
        
        return self.df

In [15]:
import pandas as pd

# Case 1 - existing data frame 
df = pd.DataFrame()
df['product_id'] = [i + 123 for i in range(25)]
df.head()

   product_id
0         123
1         124
2         125
3         126
4         127

In [16]:
fakeGen = FakeDataGenerator(df) # I'm creating instance using existing df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')

,product_id,shipping_address,billing_address,customer_phone
0,123,"95933 Joseph Meadow\nSouth Anthonystad, IA 36853","0093 Waters Courts\nSolomonburgh, SC 15928",(601)665-6093x158
1,124,"4977 Young Pine\nHaileyburgh, OH 69060","531 Wilson Curve\nNorth Traceyland, MN 19160",553.488.1404x0571
2,125,"7022 James Lodge Apt. 884\nWallaceville, NV 77445","7641 Alexis Vista Suite 844\nSouth Erica, NM 2...",494.076.1435x6233
3,126,"5093 Reed Island\nNorth Cynthia, VA 76188","221 Fowler Forks\nWest Barbarahaven, OR 51406",001-110-438-8706x899
4,127,"409 Michelle Skyway Apt. 917\nWest Ryanberg, C...","307 Mitchell Pine\nFaulknermouth, CA 53286",(363)656-1408
5,128,"3709 Moreno Field Apt. 539\nChavezbury, DC 10491","8615 Butler Underpass Suite 932\nMyersport, WY...",001-820-733-8850x3363
6,129,"90929 Henderson Lights\nNorth Andrewville, MN ...","3118 Lee Drive\nLake Travis, VT 04351",(490)981-2823x433
7,130,"265 Reese Gateway Suite 184\nNorth Aliciaberg,...","492 James Streets Suite 666\nAllenberg, OK 41661",281.581.6682x481
8,131,"446 Frank Crest Suite 428\nDawnton, NE 33735","0077 Michael Isle Apt. 420\nEast Bobbychester,...",+1-148-048-4673x386
9,132,"272 Patrick Springs\nEast Dustin, WA 71287",084 Hayden Expressway Suite 290\nSouth Wandasi...,144.993.3670
10,133,"932 David Cape Suite 412\nNorth Caitlinland, N...","8812 Hines Place\nJeromefurt, MA 89750",184-432-9003
11,134,"38682 Daniel Knolls\nTaylorstad, MD 71510","3428 Marshall Trail Apt. 902\nPort Meagan, MI ...",054.962.9994
12,135,"5539 Reese Creek Apt. 677\nNew Edwardside, IL ...","019 James Green\nCynthiastad, ND 50558",526-204-0129
13,136,"PSC 3698, Box 3798\nAPO AP 16045","6748 Joshua Harbors Suite 705\nNew Timothy, TX...",317.508.4377x3012
14,137,"001 Nolan Wall\nJonesstad, PA 54151","305 James Stravenue\nBurgessview, KS 35115",222.197.0164x2927
15,138,"85959 Strong Street\nDustinville, MS 90110","596 Davis Trafficway Suite 488\nMillermouth, W...",001-496-998-3035
16,139,"8218 Ryan Walk\nNew Greg, MS 84734","478 Joshua Ports Suite 226\nSouth Bruce, MT 97423",(121)983-3340
17,140,"5298 Carlson Expressway\nTaylortown, KS 07058","6440 Michael Crossing Apt. 323\nNew Eric, WV 1...",+1-467-766-5402x7949
18,141,"882 Darryl Summit\nPort Julieberg, PA 62618","733 Parrish Branch Suite 352\nJamesborough, TX...",(435)007-5003x1961
19,142,"8447 Smith Inlet\nNorth Joseph, WA 92525","0922 Amanda Rapid\nLake Patriciastad, HI 49584",376-777-9487
20,143,"4004 Amanda Grove Apt. 461\nJacobborough, MA 7...","08780 Nguyen Ford Apt. 397\nWest Ashley, OK 11548",125.715.4573x04273
21,144,"9480 Martinez Curve\nPort Michaelbury, GA 74638","0847 Donald Plains\nGomezshire, SD 42956",429-582-8636
22,145,"481 Vazquez Pine Suite 018\nWest Susanland, IN...","413 Sherri Island Apt. 607\nTylerview, NJ 31002",196.520.8081
23,146,"94582 Antonio Corners Suite 811\nWest Joanna, ...","3912 Lopez Plaza\nRothstad, ND 33898",890-412-2237
24,147,"912 Rich Lodge Suite 772\nEast Bobby, MN 94279",Unit 6041 Box 6193\nDPO AP 01853,841.146.4725

In [17]:
# Case 2 - no dataframe

fakeGen = FakeDataGenerator() # no df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')
fakeGen.add_random_number('sale_count', 10, 100)

,shipping_address,billing_address,customer_phone,sale_count
0,50302 Catherine Harbor Suite 668\nJacksonburgh...,"30138 Cameron Parkway Suite 817\nHartland, MO ...",912-211-4830,83
1,"195 Colleen Loaf Apt. 602\nRodriguezbury, CA 9...","9212 Scott Vista Apt. 724\nGibsonville, IA 87591",+1-643-182-3361,30
2,"0409 Harrington Ford Suite 724\nWest Heiditon,...","7152 Carter Ridge Apt. 098\nBakertown, WY 38072",123.746.0176x144,68
3,"510 Robin Avenue\nRonaldmouth, MD 36256","387 Daniel Motorway Suite 094\nEast Emily, VT ...",734-038-8215x826,32
4,"19498 Andrew Station\nWest Jeffreyland, ID 04814","32422 Romero Creek\nPatriciamouth, ME 33791",(898)074-3186x21716,92

In [51]:
#print(data.phone_number())

+1-649-640-3981x3418